Added Business Invite SDK endpoints and docs
xedi/sdk-js pull request #115
Opened 2020-10-27 13:43 UTC by adamwiteszczak

2020-10-27 14:14 UTC, midmiddleton submitted a review, later dismissed
Nice : 👍

2020-11-16 11:22 UTC, midmiddleton submitted a review, later dismissed

2020-11-16 14:10 UTC, Smudge3806 requested changes
Some small changes required... not bad

2020-11-16 14:10 UTC, Smudge3806 commented on docs/content/usage/businessinvites.mdx
> +    ]
This syntax is not correct

2020-11-16 14:10 UTC, Smudge3806 commented on docs/content/usage/businessinvites.mdx
> +    ]
Syntax invalid

2020-11-16 14:10 UTC, Smudge3806 commented on docs/content/usage/businessinvites.mdx
> +}
Syntax incorrect

2020-11-16 14:18 UTC, adamwiteszczak commented on docs/content/usage/businessinvites.mdx
> +    ]
Whoops! Corrected!

2020-11-16 14:18 UTC, adamwiteszczak commented on docs/content/usage/businessinvites.mdx
> +    ]
Whoops! Corrected!

2020-11-16 14:18 UTC, adamwiteszczak commented on docs/content/usage/businessinvites.mdx
> +}
Whoops! Corrected!

2020-11-16 15:05 UTC, Smudge3806 approved these changes

2020-11-16 16:13 UTC, merged