Feat/password update fix
xedi/sdk-js pull request #126
Opened 2020-12-07 12:13 UTC by adamwiteszczak

Added confirm password param to be sent to api for change password endpoint

2020-12-07 12:17 UTC, Smudge3806 reviewed
Happy with this from a technical perspective... @CallumEddisford is this good from a behaviour expectation?

2020-12-07 12:27 UTC, CallumEddisford commented
I usually steer clear of adding loads of paramaters like so:
```
changePassword(userUuid: Xuid<SupportedXuid.User>, newPassword: string, confirmPassword: string, currentPassword: string)
```
This is the way would prefer for now
```
changePassword(userUuid: Xuid<SupportedXuid.User>, params: Object)
```
Really for consistency this should be
```
changePassword(password: Password)
```
where password data:
```
{
    user_id: "xxxx",
    old_password: "old pass",
    password: "new",
    password_confirmation: "new"
}
```

All acomplish the same so happy for what you like, I'd go with the last option where it has a model in SDK

2020-12-07 16:06 UTC, adamwiteszczak commented
> I usually steer clear of adding loads of paramaters like so:
> 
> ```
> changePassword(userUuid: Xuid<SupportedXuid.User>, newPassword: string, confirmPassword: string, currentPassword: string)
> ```
> 
> This is the way would prefer for now
> 
> ```
> changePassword(userUuid: Xuid<SupportedXuid.User>, params: Object)
> ```
> 
> Really for consistency this should be
> 
> ```
> changePassword(password: Password)
> ```
> 
> where password data:
> 
> ```
> {
>     user_id: "xxxx",
>     old_password: "old pass",
>     password: "new",
>     password_confirmation: "new"
> }
> ```
> 
> All acomplish the same so happy for what you like, I'd go with the last option where it has a model in SDK

@CallumEddisford  @Smudge3806 I updated the various endpoints and paths to pass an array of values rather than seperate and created a new PasswordChange model in what I think is the correct way. Hope this is better!

2020-12-07 16:07 UTC, Smudge3806 submitted a review, later dismissed
Good from a technical perspective 👍

2020-12-07 16:14 UTC, CallumEddisford commented
`PasswordChange` Model should just be called `Password`?

That model should also have user_id inline with the table

2020-12-07 16:16 UTC, CallumEddisford requested changes

2020-12-07 16:16 UTC, CallumEddisford commented on src/Services/Auth.ts
> +    changePassword(userUuid: Xuid<SupportedXuid.User>, params: PasswordChange)
```suggestion
    changePassword(params: Password)
```

2020-12-07 16:16 UTC, CallumEddisford commented on src/Services/Auth.ts
> +                `1/auth/accounts/${userUuid}/password`, params)
```suggestion
                `1/auth/accounts/${params.user_id}/password`, params)
```

2020-12-07 16:16 UTC, CallumEddisford commented on src/Models/PasswordChange.ts
> +}
New empty line

2020-12-07 16:16 UTC, CallumEddisford commented on src/Models/PasswordChange.ts
> +    current_password: string;
user_id

2020-12-07 16:16 UTC, CallumEddisford commented on src/Models/PasswordChange.ts
> +export default interface PasswordChange extends Object {
`
```suggestion
export default interface Password extends Object {
```

2020-12-07 16:17 UTC, CallumEddisford commented on src/Models/PasswordChange.ts
> +    current_password: string;
```
user_id: Xuid<SupportedXuid.User>
```

2020-12-07 16:41 UTC, adamwiteszczak commented
@CallumEddisford All changes made!

2020-12-09 10:21 UTC, Smudge3806 approved these changes

2020-12-09 10:21 UTC, Smudge3806 commented on docs/content/usage/auth.mdx
> +Xedi.Auth.changePassword({ user_id: '92ac7274-9369-11ea-9521-01002da17977',  password: "new-password", password_confirmation: "new-password", current_password: "old-password" });
Might be worth breaking this over a number of lines for readabilities sake #nonblocking

2020-12-09 15:43 UTC, CallumEddisford approved these changes

2020-12-09 16:02 UTC, merged