[Git issue 28]Docs/users api
xedi/sdk-js pull request #92
Opened 2020-09-03 10:19 UTC by JonathanSwallow

2020-09-03 12:27 UTC, Smudge3806 requested changes
One minor typo correction and one question

2020-09-03 12:27 UTC, Smudge3806 commented on docs/content/usage/users.mdx
> +### list
```suggestion
### List
```

2020-09-03 12:27 UTC, Smudge3806 commented on docs/content/usage/users.mdx
> +### list
Is List paginated?

2020-09-03 13:26 UTC, JonathanSwallow commented on docs/content/usage/users.mdx
> +### list
List is not paginated :+1:

2020-09-04 08:50 UTC, Smudge3806 approved these changes

2020-09-04 08:50 UTC, merged